version: "3.9"
services:
  api:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile-${ENV}
    container_name: api
    ports:
      - "5000:5000"
    volumes: ['./backend:/app']
  ui:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile-${ENV}
    container_name: ui
    ports:
      - "8080:80"
      - "8081:8080" # development mode
    volumes:
      - ./frontend:/app
      - ./app/node_modules