version: "3.9"
services:
  api:
    restart: always
    build:
      context: ./backend
      dockerfile: docker/Dockerfile-production
    container_name: api
    expose:
      - "8000"
    volumes:
      - web-data:/usr/src/app/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "5000:80"
    volumes:
      - ./backend/static:/www/static
      - web-data:/usr/src/app/static
    links:
      - api:api
  ui:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile-production
    container_name: ui
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - ./app/node_modules

volumes:
  web-data: