version: "3.9"
services:
  api:
    build: ./backend
    container_name: api
    ports:
      - "5000:5000"
    volumes: ['./backend:/app']
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile-${ENV}
    container_name: ui
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - ./app/node_modules