# pull official base image
FROM python:3.9.5-slim

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . .

# copy database creator script to /tmp/
COPY ./db/createDatabase.py /tmp/

# creates data directory. Our DB files will live here.
RUN mkdir /data

# create and seed the database
RUN python3 /tmp/createDatabase.py